### PR TITLE
my about page

### PR DESCRIPTION
**Pull request by lillian-busingye**
my about page

### CODE REVIEW

**Comment by lillian-busingye** [comment]
@Ann-Barnshaw kindly review my about page.

**Comment by Ann-Barnshaw** [comment]
@lillian-busingye  looks good to me.

Great job!

**Comment by lillian-busingye** [comment]
@Ann-Barnshaw thank you

**Comment by Ann-Barnshaw** [comment]
@lillian-busingye you are welcome

**Pull request merged**
